services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"

  nginx:
    build: .
    container_name: nginx-docker-project
    ports:
      - "8080:80"
    depends_on:
      - backend
